### ISSUE TITLE
sudo: bin/generate_encryption_key: command not found

### ISSUE THREAD

**Issue by TheRealNeil** [intercity/intercity#26]
I am following the installation instructions and came across this error.  It looks like its only in the master branch.

**Comment by jvanbaarsen** [comment]
@TheRealNeil Thanks for creating this issue. We are not activily maintaining this version of Intercity. I would like to point you towards: https://github.com/intercity/intercity-next (Which is the new version of IC). This week I'll be working on proper installation instructions.

If you feel really adventurous, you can give it a try via https://github.com/intercity/intercity-docker.
